name: Aggiorna CSV Anagrafica Impianti

on:
  schedule:
    - cron: '0 10 * * *' # ogni giorno alle 5:00 UTC (7:00 italiane)
  workflow_dispatch: # permette anche di farlo partire a mano

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Scarica CSV dal MIMIT
      run: |
        mkdir -p ./public/data
        curl -L --retry 5 --retry-delay 10 https://www.mimit.gov.it/images/exportCSV/anagrafica_impianti_attivi.csv -o ./public/data/anagrafica_impianti_attivi.csv

    - name: Commit e push se cambiato
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ./public/data/anagrafica_impianti_attivi.csv
        git diff --staged --quiet || git commit -m "Aggiornamento automatico anagrafica impianti $(date)"
        git push
