name: Aggiorna CSV Prezzo alle 8

on:
  schedule:
    - cron: '0 7 * * *' # ogni giorno alle 5:00 UTC (7:00 italiane)
  workflow_dispatch: # permette anche di avviarlo manualmente

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Scarica CSV dal MIMIT (prezzo_alle_8.csv)
      run: |
        mkdir -p ./public/data
        curl -L --retry 5 --retry-delay 10 https://www.mimit.gov.it/images/exportCSV/prezzo_alle_8.csv -o ./public/data/prezzo_alle_8.csv

    - name: Commit e push se cambiato
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ./public/data/prezzo_alle_8.csv
        git diff --staged --quiet || git commit -m "Aggiornamento automatico prezzo_alle_8.csv $(date)"
        git push
